In [73]:
import pandas as pd
import numpy as np

df = pd.DataFrame({'A' : ['foo', 'bar', 'foo', 'bar',
                            'foo', 'bar', 'foo', 'foo'],
                    'B' : ['one', 'one', 'two', 'three',
                          'two', 'two', 'one', 'three'],
                   'C' : np.random.randn(8),
                   'D' : np.random.randn(8)})
df

A      B         C         D
0  foo    one  1.735494 -1.133420
1  bar    one  0.677940 -0.483373
2  foo    two -0.671281  1.450522
3  bar  three  1.186065  1.312236
4  foo    two -1.755419 -0.499020
5  bar    two -1.091418 -0.276020
6  foo    one -0.521854  0.737679
7  foo  three -0.169096  1.053095

In [8]:
df_0=df.groupby('A').count()
print(df_0)

     B  C  D
A           
bar  3  3  3
foo  5  5  5


In [9]:
print(df.groupby(['A', 'B']).count())

           C  D
A   B          
bar one    1  1
    three  1  1
    two    1  1
foo one    2  2
    three  1  1
    two    2  2


In [10]:
grouped=df.groupby(['A'])
grouped["C"]

In [11]:
df.groupby(['A', 'B']).agg([np.sum, np.mean, np.std])

C                            D                    
                sum      mean      std       sum      mean       std
A   B                                                               
bar one   -0.135955 -0.135955      NaN -1.710693 -1.710693       NaN
    three  1.193230  1.193230      NaN -0.994709 -0.994709       NaN
    two   -0.555800 -0.555800      NaN -0.231174 -0.231174       NaN
foo one   -1.275457 -0.637729  1.04123 -1.100008 -0.550004  0.668820
    three -0.218193 -0.218193      NaN -2.111280 -2.111280       NaN
    two    2.069984  1.034992  1.93231  0.125749  0.062874  0.213159

In [96]:
df["label"]=df["C"].apply(lambda x: 1 if x>0 else 0)
df

A      B         C         D  label
0  foo    one  1.735494 -1.133420      1
1  bar    one  0.677940 -0.483373      1
2  foo    two -0.671281  1.450522      0
3  bar  three  1.186065  1.312236      1
4  foo    two -1.755419 -0.499020      0
5  bar    two -1.091418 -0.276020      0
6  foo    one -0.521854  0.737679      0
7  foo  three -0.169096  1.053095      0

In [107]:
df.groupby(["A","B"])["C","D"].count()

C  D
A   B          
bar one    1  1
    three  1  1
    two    1  1
foo one    2  2
    three  1  1
    two    2  2

In [112]:
df.groupby(["A","B"])["C","D"].count().reset_index().merge(df,how="inner",on=["A","B"])

A      B  C_x  D_x       C_y       D_y  label
0  bar    one    1    1  0.677940 -0.483373      1
1  bar  three    1    1  1.186065  1.312236      1
2  bar    two    1    1 -1.091418 -0.276020      0
3  foo    one    2    2  1.735494 -1.133420      1
4  foo    one    2    2 -0.521854  0.737679      0
5  foo  three    1    1 -0.169096  1.053095      0
6  foo    two    2    2 -0.671281  1.450522      0
7  foo    two    2    2 -1.755419 -0.499020      0

In [128]:
left=df.groupby(["A","B"])["C","D"].count().reset_index()
left

A      B  C  D
0  bar    one  1  1
1  bar  three  1  1
2  bar    two  1  1
3  foo    one  2  2
4  foo  three  1  1
5  foo    two  2  2

In [147]:
right=df[["A","B","label"]].groupby(["A","B"]).sum()
right

label
A   B           
bar one        1
    three      1
    two        0
foo one        1
    three      0
    two        0

In [150]:
pd.merge(left,right.reset_index(),how="inner",on=["A","B"])

A      B  C  D  label
0  bar    one  1  1      1
1  bar  three  1  1      1
2  bar    two  1  1      0
3  foo    one  2  2      1
4  foo  three  1  1      0
5  foo    two  2  2      0

In [105]:
df.groupby(["A","B"]).count().reset_index()

A      B  C  D  label
0  bar    one  1  1      1
1  bar  three  1  1      1
2  bar    two  1  1      1
3  foo    one  2  2      2
4  foo  three  1  1      1
5  foo    two  2  2      2

In [90]:
new_df=df.groupby(['A', 'B']).agg([np.sum, np.mean, np.std])
print (new_df["C"]["sum"].values)
print (np.array(new_df["C"]["sum"]).ravel())
print (new_df["C"]["sum"])


# from sklearn import linear_model
# clf = linear_model.Ridge (alpha = .5)
# clf.fit (new_df["C"]["sum"].values,new_df["D"]["mean"].values) 
# Ridge(alpha=0.5, copy_X=True, fit_intercept=True, max_iter=None,
#       normalize=False, random_state=None, solver='auto', tol=0.001)
# clf.coef_

[ 0.67793969  1.18606514 -1.091418    1.21363956 -0.16909639 -2.42669954]
[ 0.67793969  1.18606514 -1.091418    1.21363956 -0.16909639 -2.42669954]
A    B    
bar  one      0.677940
     three    1.186065
     two     -1.091418
foo  one      1.213640
     three   -0.169096
     two     -2.426700
Name: sum, dtype: float64


In [14]:
df_0=df.groupby('A')
df_0["B"].count()

A
bar    3
foo    5
Name: B, dtype: int64

In [17]:
sf = pd.Series([1, 1, 2, 3, 3, 3])
sf.groupby(sf)

In [21]:
sf.groupby(sf).filter(lambda x: x.sum()>2)

3    3
4    3
5    3
dtype: int64

In [22]:
for i in sf.groupby(sf):
    print(i)

(1, 0    1
1    1
dtype: int64)
(2, 2    2
dtype: int64)
(3, 3    3
4    3
5    3
dtype: int64)


In [30]:

dates = np.asarray(pd.date_range('1/1/2000', periods=8))
df = pd.DataFrame(np.random.randn(8, 4), index=dates, columns=['A', 'B', 'C', 'D'])
df

A         B         C         D
2000-01-01 -0.159289  0.635359  0.347169  0.951949
2000-01-02 -0.963270  0.037915 -0.090537 -0.954093
2000-01-03 -0.397243 -0.496035  0.221576  1.085912
2000-01-04  0.331746 -0.896486 -1.894054 -0.115327
2000-01-05  0.499429  1.536600 -0.753343 -0.275946
2000-01-06 -1.495066 -0.370580  0.579039  1.694034
2000-01-07 -0.481420  0.935092  1.984819  0.191758
2000-01-08 -0.519380  2.313890  0.157449 -0.017473

In [31]:
df.ix[df["A"]>0,:]

A         B         C         D
2000-01-04  0.331746 -0.896486 -1.894054 -0.115327
2000-01-05  0.499429  1.536600 -0.753343 -0.275946

In [39]:
df.ix[df["A"]==0.331746,:]

Empty DataFrame
Columns: [A, B, C, D]
Index: []

In [33]:
df.ix[df["A"]>0,["C","D"]]

C         D
2000-01-04 -1.894054 -0.115327
2000-01-05 -0.753343 -0.275946

In [42]:
df=pd.DataFrame({"a":list([1,2,3,4,5,6,5,5,5]),"b":list([4,5,6,7,9,6,7,8,9])})
df

a  b
0  1  4
1  2  5
2  3  6
3  4  7
4  5  9
5  6  6
6  5  7
7  5  8
8  5  9

In [44]:
df.ix[df["a"]==5,:]

a  b
4  5  9
6  5  7
7  5  8
8  5  9

In [69]:
from sklearn.preprocessing import OneHotEncoder
enc=OneHotEncoder()
enc.fit(df.ix[df["a"]==5,"b"])
df2=enc.transform(df.ix[df["a"]==5,"b"]).toarray()
print(df2)

[[ 1.  1.  1.  1.]]


/opt/anaconda3/lib/python3.5/site-packages/sklearn/utils/validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
/opt/anaconda3/lib/python3.5/site-packages/sklearn/utils/validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)


In [71]:
df3=pd.get_dummies(df.ix[df["a"]==5,"b"])
df3

7    8    9
4  0.0  0.0  1.0
6  1.0  0.0  0.0
7  0.0  1.0  0.0
8  0.0  0.0  1.0